#!/usr/bin/env python3
"""Generates app/src/main/res/raw/watchface.xml from the template.

A ColorOption in the Watch Face Format holds at most five colors, but the
design uses ten color roles. So the theme is a ListConfiguration instead: each
<ThemeSwitch> block of watchface/watchface.template.xml is copied once per
theme from watchface/themes.json, with @{role} replaced by that theme's color.

Usage: build_watchface.py [--check]
  --check  exit 1 if the generated file is out of date instead of writing it
"""
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEMPLATE = os.path.join(ROOT, "watchface", "watchface.template.xml")
THEMES = os.path.join(ROOT, "watchface", "themes.json")
OUTPUT = os.path.join(ROOT, "app", "src", "main", "res", "raw", "watchface.xml")

SWITCH = re.compile(r'(?P<indent>[ \t]*)<ThemeSwitch name="(?P<name>\w+)" width="(?P<w>\d+)" '
                    r'height="(?P<h>\d+)">\n(?P<body>[\s\S]*?)\n[ \t]*</ThemeSwitch>')
COMMENT = re.compile(r"[ \t]*<!--[\s\S]*?-->\n?")
ROLE = re.compile(r"@\{(\w+)\}")


def shift(text, spaces):
    pad = " " * spaces
    return "\n".join(pad + line if line.strip() else line for line in text.split("\n"))


def colorize(body, roles, colors):
    def repl(m):
        if m.group(1) not in roles:
            raise SystemExit(f"unknown color role @{{{m.group(1)}}}")
        return "#ff" + colors[roles.index(m.group(1))].lstrip("#").lower()
    return ROLE.sub(repl, body)


def expand(m, cfg):
    ind, name, w, h = m.group("indent"), m.group("name"), m.group("w"), m.group("h")
    body = COMMENT.sub("", m.group("body"))
    options = []
    for i, theme in enumerate(cfg["themes"]):
        inner = shift(colorize(body, cfg["roles"], theme["colors"]), 6)
        options.append(f'{ind}    <ListOption id="{i}">\n'
                       f'{ind}      <Group name="{name}_{theme["id"]}" x="0" y="0" width="{w}" height="{h}">\n'
                       f'{inner}\n'
                       f'{ind}      </Group>\n'
                       f'{ind}    </ListOption>')
    return (f'{ind}<Group name="{name}" x="0" y="0" width="{w}" height="{h}">\n'
            f'{ind}  <ListConfiguration id="theme">\n' + "\n".join(options) + "\n"
            f'{ind}  </ListConfiguration>\n'
            f'{ind}</Group>')


def configuration(cfg):
    default = next(i for i, t in enumerate(cfg["themes"]) if t["id"] == cfg["default"])
    opts = "\n".join(f'      <ListOption id="{i}" displayName="theme_{t["id"]}" icon="theme_{t["id"]}" />'
                     for i, t in enumerate(cfg["themes"]))
    flavors = "\n".join(f'      <Flavor id="{t["id"]}" displayName="theme_{t["id"]}" icon="theme_{t["id"]}">\n'
                        f'        <Configuration id="theme" optionId="{i}" />\n'
                        f'      </Flavor>' for i, t in enumerate(cfg["themes"]))
    return (f'  <UserConfigurations>\n'
            f'    <ListConfiguration id="theme" displayName="theme_label" defaultValue="{default}">\n'
            f'{opts}\n'
            f'    </ListConfiguration>\n'
            f'    <Flavors defaultValue="{cfg["default"]}">\n'
            f'{flavors}\n'
            f'    </Flavors>\n'
            f'  </UserConfigurations>')


def generate():
    cfg = json.load(open(THEMES))
    for t in cfg["themes"]:
        assert len(t["colors"]) == len(cfg["roles"]), t["id"]
    src = open(TEMPLATE).read()
    header_end = src.index("-->") + 3
    head = ('<?xml version="1.0" encoding="utf-8"?>\n'
            "<!-- GENERATED by tools/build_watchface.py from watchface/watchface.template.xml\n"
            "     and watchface/themes.json. Do not edit by hand: run \"make generate\". -->")
    body = src[header_end:]
    body = body.replace("  <!-- @THEME_CONFIGURATION@ -->", configuration(cfg))
    body = SWITCH.sub(lambda m: expand(m, cfg), body)
    if "ThemeSwitch" in body or ROLE.search(body):
        raise SystemExit("unexpanded ThemeSwitch or color role left in output")
    return head + body


def main():
    out = generate()
    if "--check" in sys.argv:
        current = open(OUTPUT).read() if os.path.exists(OUTPUT) else ""
        if current != out:
            print("watchface.xml is out of date: run 'make generate'")
            sys.exit(1)
        print("watchface.xml is up to date")
        return
    with open(OUTPUT, "w") as f:
        f.write(out)
    print(f"wrote {os.path.relpath(OUTPUT, ROOT)} ({out.count(chr(10)) + 1} lines)")


if __name__ == "__main__":
    main()
